game.AddParticles( "particles/ammo_cache_ins.pcf" )
game.AddParticles( "particles/asw_environmental_fx.pcf" )
game.AddParticles( "particles/asw_muzzle_fx.pcf" )
game.AddParticles( "particles/asw_order_fx.pcf" )
game.AddParticles( "particles/asw_precipitation.pcf" )

game.AddParticles( "particles/asw_spark_fx.pcf" )
game.AddParticles( "particles/asw_tracer_fx.pcf" )
game.AddParticles( "particles/asw_weapon_fx.pcf" )
game.AddParticles( "particles/asw_welding_fx.pcf" )

game.AddParticles( "particles/blood_fx.pcf" )
game.AddParticles( "particles/blood_impact.pcf" )
game.AddParticles( "particles/burning_fx.pcf" )
game.AddParticles( "particles/burningplayer.pcf" )
game.AddParticles( "particles/burningplayer_dx80.pcf" )

game.AddParticles( "particles/ins_smokegrenade.pcf" )
game.AddParticles( "particles/doi_destructible_fx.pcf" )
game.AddParticles( "particles/doi_explosion_fx.pcf" )
game.AddParticles( "particles/doi_explosion_fx_b.pcf" )
game.AddParticles( "particles/doi_explosion_fx_c.pcf" )
game.AddParticles( "particles/doi_explosion_fx_grenade.pcf" )
game.AddParticles( "particles/doi_explosion_fx_new.pcf" )
game.AddParticles( "particles/doi_explosions_smoke.pcf" )

game.AddParticles( "particles/doi_impact_fx.pcf" )
game.AddParticles( "particles/doi_weapon_fx.pcf" )
game.AddParticles( "particles/explosion_fx_ins.pcf" )
game.AddParticles( "particles/explosion_fx_ins_b.pcf" )

game.AddParticles( "particles/muzzleflashes_test.pcf" )


--
PrecacheParticleSystem( "port_smoke" )
PrecacheParticleSystem( "barrel_smoke" )
PrecacheParticleSystem( "barrel_smoke_trail" )
PrecacheParticleSystem( "barrel_smoke_trail_b" )
PrecacheParticleSystem( "muzzle_smoke_b" )
PrecacheParticleSystem( "muzzle_smoke_c" )
PrecacheParticleSystem( "muzzle_smoke_d" )
PrecacheParticleSystem( "muzzle_smoke_shot_b" )
PrecacheParticleSystem( "muzzle_supressed_smoke_b" )
PrecacheParticleSystem( "muzzle_supressed_smoke_d" )
PrecacheParticleSystem( "muzzleflash_1" )
PrecacheParticleSystem( "muzzleflash_3" )
PrecacheParticleSystem( "muzzleflash_4" )
PrecacheParticleSystem( "muzzleflash_5" )
PrecacheParticleSystem( "muzzleflash_6" )
PrecacheParticleSystem( "muzzleflash_ak47" )
PrecacheParticleSystem( "muzzleflash_m14" )
PrecacheParticleSystem( "muzzleflash_g3" )
PrecacheParticleSystem( "muzzleflash_FAMAS" )
PrecacheParticleSystem( "muzzleflash_shotgun" )
PrecacheParticleSystem( "muzzleflash_smg" )
PrecacheParticleSystem( "muzzleflash_suppressed" )

--MG42
PrecacheParticleSystem( "muzzleflash_mg42_1p_b" )
PrecacheParticleSystem( "muzzleflash_mg42_1p_smoke" )
PrecacheParticleSystem( "muzzleflash_mg42_1p_core_b" )
PrecacheParticleSystem( "muzzleflash_mg42_1p_glow_b" )
PrecacheParticleSystem( "muzzleflash_mg42_1p_glow" )
PrecacheParticleSystem( "muzzleflash_mg42_1p_sparks" )
PrecacheParticleSystem( "muzzleflash_mg42_1p_splits" )
PrecacheParticleSystem( "muzzleflash_mg42_1p_spark_trail" )
PrecacheParticleSystem( "muzzleflash_mg42_1p_c" )
PrecacheParticleSystem( "muzzleflash_mg42_1p" )
PrecacheParticleSystem( "muzzleflash_mg42_1p_core" )
--MP40
PrecacheParticleSystem( "muzzleflash_mp40_1p_b" )
PrecacheParticleSystem( "muzzleflash_mp40_1p_core_b" )
PrecacheParticleSystem( "muzzleflash_mp40_1p" )
PrecacheParticleSystem( "muzzleflash_mp40_1p_core" )
PrecacheParticleSystem( "muzzleflash_mp40_1p_glow" )
PrecacheParticleSystem( "muzzleflash_mp40_1p_glow_b" )
PrecacheParticleSystem( "muzzleflash_mp40_1p_spark_trail" )
--M1919
PrecacheParticleSystem( "muzzleflash_m1919_1p_core" )
PrecacheParticleSystem( "muzzleflash_m1919_1p_core_c" )
PrecacheParticleSystem( "muzzleflash_m1919_1p_sparks" )
PrecacheParticleSystem( "muzzleflash_m1919_1p" )
PrecacheParticleSystem( "muzzleflash_m1919_1p_glow" )
PrecacheParticleSystem( "muzzleflash_m1919_1p_glow_b" )
PrecacheParticleSystem( "muzzleflash_m1919_1p_spark_trail" )
PrecacheParticleSystem( "muzzleflash_m1919_1p_flame" )
PrecacheParticleSystem( "muzzleflash_m1919_1p_flame_b" )
PrecacheParticleSystem( "muzzleflash_m1919_1p_b" )
PrecacheParticleSystem( "muzzleflash_m1919_1p_flame_b_copy" )
PrecacheParticleSystem( "muzzleflash_m1919_1p_core_d" )

--Thompson
PrecacheParticleSystem( "muzzleflash_thompson_1p_spark_trail" )
PrecacheParticleSystem( "muzzleflash_thompson_1p" )
PrecacheParticleSystem( "muzzleflash_thompson_1p_core" )
PrecacheParticleSystem( "muzzleflash_thompson_1p_split" )
PrecacheParticleSystem( "muzzleflash_thompson_1p_glow" )
PrecacheParticleSystem( "muzzleflash_thompson_1p_glow_b" )
PrecacheParticleSystem( "muzzleflash_thompson_1p_core_b" )
PrecacheParticleSystem( "muzzleflash_thompson_1p_b" )

--MG34
PrecacheParticleSystem( "muzzleflash_mg34_1p_core_b" )
PrecacheParticleSystem( "muzzleflash_mg34_1p" )
PrecacheParticleSystem( "muzzleflash_mg34_1p_core" )
PrecacheParticleSystem( "muzzleflash_mg34_1p_splits" )

--STEN
PrecacheParticleSystem( "muzzleflash_sten_1p_core" )
PrecacheParticleSystem( "muzzleflash_sten_1p" )
PrecacheParticleSystem( "muzzleflash_sten_1p_core" )

--ithica
PrecacheParticleSystem( "muzzleflash_ithica_1p_sparks" )
PrecacheParticleSystem( "muzzleflash_ithica_1p" )
PrecacheParticleSystem( "muzzleflash_ithica_1p_spark_trail" )
PrecacheParticleSystem( "muzzleflash_ithica_1p_core" )
PrecacheParticleSystem( "muzzleflash_ithica_1p_core_b" )
PrecacheParticleSystem( "muzzleflash_ithica_1p_flame" )
PrecacheParticleSystem( "muzzleflash_ithica_1p_b" )

--1911
PrecacheParticleSystem( "muzzleflash_1911_1p" )
PrecacheParticleSystem( "muzzleflash_1911_1p_core" )
PrecacheParticleSystem( "muzzleflash_1911_1p_glow" )
PrecacheParticleSystem( "muzzleflash_1911_1p_glow_b" )
PrecacheParticleSystem( "muzzleflash_1911_1p_spark_trail" )

--luger
PrecacheParticleSystem( "muzzleflash_luger_1p" )
PrecacheParticleSystem( "muzzleflash_luger_1p_core" )
PrecacheParticleSystem( "muzzleflash_luger_1p_glow" )
PrecacheParticleSystem( "muzzleflash_luger_1p_glow_b" )
PrecacheParticleSystem( "muzzleflash_luger_1p_spark_trail" )

--STG44
PrecacheParticleSystem( "muzzleflash_stg44_1p_core" )
PrecacheParticleSystem( "muzzleflash_stg44_1p" )

--M1carabin
PrecacheParticleSystem( "muzzleflash_m1carbine_1p_core" )
PrecacheParticleSystem( "muzzleflash_m1carbine_1p" )


--smoke
PrecacheParticleSystem( "muzzleflash_smoke_tiny" )
PrecacheParticleSystem( "muzzleflash_smoke_small_variant_1" )
PrecacheParticleSystem( "muzzleflash_smoke_small_variant_4" )
PrecacheParticleSystem( "muzzleflash_smoke_medium_variant_1" )
PrecacheParticleSystem( "muzzleflash_smoke_large_linger" )
PrecacheParticleSystem( "muzzleflash_smoke_small_variant_5" )
PrecacheParticleSystem( "muzzleflash_smoke_medium_linger" )
PrecacheParticleSystem( "muzzleflash_smoke_small_variant_3" )
PrecacheParticleSystem( "muzzleflash_smoke_small_variant_2" )

--Sparks
PrecacheParticleSystem( "muzzleflash_spark_trail" )
PrecacheParticleSystem( "muzzleflash_sparks" )
PrecacheParticleSystem( "muzzleflash_spark_trail_c" )


--K98
PrecacheParticleSystem( "muzzleflash_k98_1p" )
PrecacheParticleSystem( "muzzleflash_k98_1p_core" )

--GARAND
PrecacheParticleSystem( "muzzleflash_garand_1p" )
PrecacheParticleSystem( "muzzleflash_garand_1p_core" )




PrecacheParticleSystem( "muzzleflash_dust_kickup" )
PrecacheParticleSystem( "muzzleflash_spark_trail" )
PrecacheParticleSystem( "muzzleflash_1p_glow" )
PrecacheParticleSystem( "muzzleflash_tracer" )
PrecacheParticleSystem( "muzzleflash_suppressed_1p" )
PrecacheParticleSystem( "muzzleflash_empty" )
PrecacheParticleSystem( "muzzleflash_spark_trail_b" )
PrecacheParticleSystem( "muzzleflash_bar_1p" )

--INS


--BEMBS

PrecacheParticleSystem( "doi_destructible_wall" )
PrecacheParticleSystem( "doi_destructible_wall_rocks" )
PrecacheParticleSystem( "doi_destructible_wall_rocks_b" )
PrecacheParticleSystem( "doi_destructible_wall_smoke" )
PrecacheParticleSystem( "doi_destructible_wall_impact_smoke_center" )
PrecacheParticleSystem( "doi_destructible_wall_rocks_c" )
PrecacheParticleSystem( "doi_destructible_wall_impact" )
PrecacheParticleSystem( "doi_destructible_wall_impact_smoke" )
					    
PrecacheParticleSystem( "generic_crater_smoke_big" )
PrecacheParticleSystem( "generic_crater_smoke" )
PrecacheParticleSystem( "generic_nearglow_b" )
PrecacheParticleSystem( "generic_nearglow" )
					    
PrecacheParticleSystem( "doi_grenade_explosion_smoke_b" )
PrecacheParticleSystem( "doi_grenade_explosion_debris_b" )
PrecacheParticleSystem( "doi_grenade_explosion_sparkTrail" )
PrecacheParticleSystem( "doi_grenade_explosion_debris_d" )
PrecacheParticleSystem( "doi_grenade_explosion_flames_b" )
PrecacheParticleSystem( "doi_grenade_explosion_smokeTrails" )
PrecacheParticleSystem( "doi_grenade_explosion_flash_b" )
PrecacheParticleSystem( "doi_grenade_explosion_smoke_e" )
PrecacheParticleSystem( "doi_grenade_explosion_sparks" )
PrecacheParticleSystem( "doi_grenade_explosion_sparks_b" )
PrecacheParticleSystem( "doi_grenade_explosion_sparks_c" )
PrecacheParticleSystem( "doi_grenade_explosion_sparks_d" )
PrecacheParticleSystem( "doi_grenade_explosion_debris" )
PrecacheParticleSystem( "doi_grenade_explosion_debris_c" )
PrecacheParticleSystem( "doi_grenade_explosion_shockwave" )
PrecacheParticleSystem( "doi_grenade_explosion_spikes_b" )
PrecacheParticleSystem( "doi_grenade_explosion_spikes" )
PrecacheParticleSystem( "doi_grenade_explosion_spikes_c" )
PrecacheParticleSystem( "doi_grenade_explosion_smoke_c" )
PrecacheParticleSystem( "doi_grenade_explosion_flames" )
PrecacheParticleSystem( "doi_grenade_explosion_smoke_d" )
PrecacheParticleSystem( "doi_grenade_explosion_smoke" )
PrecacheParticleSystem( "doi_grenade_explosion_smoke_linger" )
PrecacheParticleSystem( "doi_grenade_explosionOLD" )
PrecacheParticleSystem( "doi_grenade_explosion_sparkTrail_b" )
PrecacheParticleSystem( "doi_grenade_explosion_debris_small" )
PrecacheParticleSystem( "doi_grenade_explosion" )
PrecacheParticleSystem( "doi_grenade_explosion_spikes_target" )
PrecacheParticleSystem( "doi_grenade_explosion_flame_b" )
PrecacheParticleSystem( "doi_grenade_explosion_glow_b" )
PrecacheParticleSystem( "doi_grenade_explosion_sparkBurst" )
PrecacheParticleSystem( "doi_grenade_explosion_flame" )
PrecacheParticleSystem( "doi_grenade_explosion_spikes_debris_target" )
PrecacheParticleSystem( "doi_grenade_explosion_debris_spikes" )
PrecacheParticleSystem( "doi_grenade_explosion_spikes_debris_burst" )
PrecacheParticleSystem( "doi_grenade_explosion_spikes_fast" )
PrecacheParticleSystem( "doi_grenade_explosion_smoke_ground" )
PrecacheParticleSystem( "doi_grenade_explosion_glow_c" )
PrecacheParticleSystem( "doi_grenade_explosion_debris_rocks" )
PrecacheParticleSystem( "doi_grenade_explosion_shock_smoke" )
PrecacheParticleSystem( "doi_grenade_explosion_debris_e" )
PrecacheParticleSystem( "doi_grenade_explosion_glow_d" )
					    
PrecacheParticleSystem( "doi_artillery_explosion_flash" )
PrecacheParticleSystem( "doi_artillery_explosion_debris_small" )
PrecacheParticleSystem( "doi_artillery_explosion_shockwave" )
PrecacheParticleSystem( "doi_artillery_explosion_OLD" )
PrecacheParticleSystem( "doi_artillery_explosion_smoke" )
PrecacheParticleSystem( "doi_artillery_explosion_smoke_linger" )
PrecacheParticleSystem( "doi_artillery_explosion_spikes_b" )
PrecacheParticleSystem( "doi_artillery_explosion_smoke_b" )
PrecacheParticleSystem( "doi_artillery_explosion_spikes_d" )
PrecacheParticleSystem( "doi_artillery_explosion_debris_c" )
PrecacheParticleSystem( "doi_artillery_explosion_debris_d" )
PrecacheParticleSystem( "doi_artillery_explosion_smoke_d" )
PrecacheParticleSystem( "doi_artillery_explosion_spikes_c" )
PrecacheParticleSystem( "doi_artillery_explosion_sparks" )
PrecacheParticleSystem( "doi_artillery_explosion_spikes_fast_b" )
PrecacheParticleSystem( "doi_artillery_explosion_sparkTrail" )
PrecacheParticleSystem( "doi_artillery_explosion_spikes_fast" )
PrecacheParticleSystem( "doi_artillery_explosion_spikes" )
PrecacheParticleSystem( "doi_artillery_explosion_dust_b" )
PrecacheParticleSystem( "doi_artillery_explosion_flames" )
PrecacheParticleSystem( "doi_artillery_explosion_flash_b" )
PrecacheParticleSystem( "doi_artillery_explosion_smokeTrails" )
PrecacheParticleSystem( "doi_artillery_explosion_debris_b" )
PrecacheParticleSystem( "doi_artillery_explosion_smoke_c" )
PrecacheParticleSystem( "doi_artillery_explosion_debris" )
PrecacheParticleSystem( "doi_artillery_explosion_dust" )
PrecacheParticleSystem( "doi_artillery_explosion_spikes_dirt" )
PrecacheParticleSystem( "doi_artillery_explosion_spikes_debris_target" )
PrecacheParticleSystem( "doi_artillery_explosion_spikes_debris_burst" )
PrecacheParticleSystem( "doi_artillery_explosion" )
PrecacheParticleSystem( "doi_artillery_explosion_debris_rocks" )
PrecacheParticleSystem( "doi_artillery_explosion_spikes_target" )
PrecacheParticleSystem( "doi_artillery_explosion_debris_e" )
PrecacheParticleSystem( "doi_artillery_explosion_smoke_ground" )
PrecacheParticleSystem( "doi_artillery_explosion_glow" )
PrecacheParticleSystem( "doi_artillery_explosion_glow_b" )
PrecacheParticleSystem( "doi_artillery_explosion_glow_d" )
PrecacheParticleSystem( "doi_artillery_explosion_sparkBurst" )
PrecacheParticleSystem( "doi_artillery_explosion_flame" )
PrecacheParticleSystem( "doi_artillery_explosion_sparks_b" )
PrecacheParticleSystem( "doi_artillery_explosion_glow_c" )
PrecacheParticleSystem( "doi_artillery_explosion_shock_smoke" )
					    
PrecacheParticleSystem( "doi_WParty_glows" )
PrecacheParticleSystem( "doi_WParty_glow_smoke" )
PrecacheParticleSystem( "doi_WParty_trailgroup" )
PrecacheParticleSystem( "doi_WParty_trails" )
PrecacheParticleSystem( "doi_WParty_trail_smoke" )
PrecacheParticleSystem( "doi_WParty_explosion" )
PrecacheParticleSystem( "doi_WParty_groundflames" )
PrecacheParticleSystem( "doi_WParty_smoke_linger" )
PrecacheParticleSystem( "doi_WParty_smoke" )
PrecacheParticleSystem( "doi_WParty_smoke_b" )
PrecacheParticleSystem( "doi_WParty_flames" )
PrecacheParticleSystem( "doi_WParty_spikes" )
PrecacheParticleSystem( "doi_WParty_fog" )
PrecacheParticleSystem( "doi_WParty_fog_b" )
PrecacheParticleSystem( "doi_WParty_sparks" )
PrecacheParticleSystem( "doi_WParty_sparks_b" )
PrecacheParticleSystem( "doi_WParty_flash" )
PrecacheParticleSystem( "doi_WParty_glow" )
PrecacheParticleSystem( "doi_WProcket_explosion" )
PrecacheParticleSystem( "doi_WProcket_smoke" )
PrecacheParticleSystem( "doi_WPgrenade_smoke_b" )
PrecacheParticleSystem( "doi_WProcket_spikes" )
PrecacheParticleSystem( "doi_WPgrenade_explosion" )
PrecacheParticleSystem( "doi_WPgrenade_groundflames" )
PrecacheParticleSystem( "doi_WPgrenade_trailGroup" )
PrecacheParticleSystem( "doi_WPgrenade_smoke" )
PrecacheParticleSystem( "doi_WPgrenade_sparks" )
PrecacheParticleSystem( "doi_WPgrenade_sparks_b" )
PrecacheParticleSystem( "doi_WPgrenade_flash" )
PrecacheParticleSystem( "doi_WPgrenade_trails" )
PrecacheParticleSystem( "doi_WPgrenade_trail_smoke" )
PrecacheParticleSystem( "doi_WPgrenade_sparks_c" )
					    
PrecacheParticleSystem( "doi_mortar_explosion_smoke_b" )
PrecacheParticleSystem( "doi_mortar_explosion_debris_small" )
PrecacheParticleSystem( "doi_mortar_explosion_debris_d" )
PrecacheParticleSystem( "doi_mortar_explosion_sparkTrail_b" )
PrecacheParticleSystem( "doi_mortar_explosion_debris_b" )
PrecacheParticleSystem( "doi_mortar_explosion_sparkTrail" )
PrecacheParticleSystem( "doi_mortar_explosionOLD" )
PrecacheParticleSystem( "doi_mortar_explosion_shockwave" )
PrecacheParticleSystem( "doi_mortar_explosion_smoke_linger" )
PrecacheParticleSystem( "doi_mortar_explosion_smoke_d" )
PrecacheParticleSystem( "doi_mortar_explosion_smoke_c" )
PrecacheParticleSystem( "doi_mortar_explosion_smoke_core" )
PrecacheParticleSystem( "doi_mortar_explosion_smoke_e" )
PrecacheParticleSystem( "doi_mortar_explosion_flash_b" )
PrecacheParticleSystem( "doi_mortar_explosion_spikes" )
PrecacheParticleSystem( "doi_mortar_explosion_spikes_c" )
PrecacheParticleSystem( "doi_mortar_explosion_debris" )
PrecacheParticleSystem( "doi_mortar_explosion_debris_c" )
PrecacheParticleSystem( "doi_mortar_explosion_sparks" )
PrecacheParticleSystem( "doi_mortar_explosion_sparks_b" )
PrecacheParticleSystem( "doi_mortar_explosion_sparks_c" )
PrecacheParticleSystem( "doi_mortar_explosion_smokeTrails" )
PrecacheParticleSystem( "doi_mortar_explosion_spikes_b" )
PrecacheParticleSystem( "doi_mortar_explosion_flash" )
PrecacheParticleSystem( "doi_mortar_explosion_smoke" )
PrecacheParticleSystem( "doi_mortar_explosion_sparks_d" )
PrecacheParticleSystem( "doi_mortar_explosion_flames" )
PrecacheParticleSystem( "doi_mortar_explosion" )
PrecacheParticleSystem( "doi_mortar_explosion_spikes_target" )
PrecacheParticleSystem( "doi_mortar_explosion_flame" )
PrecacheParticleSystem( "doi_mortar_explosion_shock_smoke" )
					    
PrecacheParticleSystem( "doi_compB_explosion_smoke" )
PrecacheParticleSystem( "doi_compB_explosion_smoke_b" )
PrecacheParticleSystem( "doi_compB_explosionOLD" )
PrecacheParticleSystem( "doi_compB_explosion_smoke_c" )
PrecacheParticleSystem( "doi_compB_explosion_flash_b" )
PrecacheParticleSystem( "doi_compB_explosion_debris_c" )
PrecacheParticleSystem( "doi_compB_explosion_debris_d" )
PrecacheParticleSystem( "doi_compB_explosion_spikes" )
PrecacheParticleSystem( "doi_compB_explosion_debris_b" )
PrecacheParticleSystem( "doi_compB_explosion_flames" )
PrecacheParticleSystem( "doi_compB_explosion_dust" )
PrecacheParticleSystem( "doi_compB_explosion_flash" )
PrecacheParticleSystem( "doi_compB_explosion_sparkTrail" )
PrecacheParticleSystem( "doi_compB_explosion_debris" )
PrecacheParticleSystem( "doi_compB_explosion_sparks" )
PrecacheParticleSystem( "doi_compB_explosion_flash_c" )
PrecacheParticleSystem( "doi_compB_explosion" )
PrecacheParticleSystem( "doi_compB_explosion_spikes_b" )
PrecacheParticleSystem( "doi_compB_explosion_debris_rocks" )
PrecacheParticleSystem( "doi_compB_explosion_spikes_debris_target" )
PrecacheParticleSystem( "doi_compB_explosion_spikes_debris_burst" )
PrecacheParticleSystem( "doi_compB_explosion_flame" )
PrecacheParticleSystem( "doi_compB_explosion_smoke_ground" )
					    
PrecacheParticleSystem( "doi_flak88_explosion_debris" )
PrecacheParticleSystem( "doi_flak88_explosion_sparks_trail" )
PrecacheParticleSystem( "doi_flak88_explosion_smoke" )
PrecacheParticleSystem( "doi_flak88_explosion_glow" )
PrecacheParticleSystem( "doi_flak88_trail_groups" )
PrecacheParticleSystem( "doi_flak88_explosion_trails" )
PrecacheParticleSystem( "doi_flak88_explosion_smoke_trail" )
PrecacheParticleSystem( "doi_flak88_explosion_flame_b" )
PrecacheParticleSystem( "doi_flak88_explosion_spikes_b" )
PrecacheParticleSystem( "doi_flak88_explosion_sparks_c" )
PrecacheParticleSystem( "doi_flak88_explosion_glow_b" )
PrecacheParticleSystem( "doi_flak88_explosion_gllow_smoke" )
PrecacheParticleSystem( "doi_flak88_explosion_gllow_flame" )
PrecacheParticleSystem( "doi_flak88_explosion_sparks_b" )
PrecacheParticleSystem( "doi_flak88_explosion_sparks" )
PrecacheParticleSystem( "doi_flak88_explosion_spikes" )
PrecacheParticleSystem( "doi_flak88_explosion" )
PrecacheParticleSystem( "doi_flak88_explosion_flames" )
PrecacheParticleSystem( "doi_flak88_trail_groups_b" )
PrecacheParticleSystem( "doi_flak88_explosion_trails_b" )
PrecacheParticleSystem( "doi_flak88_explosion_flame_trail" )
PrecacheParticleSystem( "doi_flak88_explosion_trail_group_b" )
					    
PrecacheParticleSystem( "doi_petrol_explosion_fire_c" )
PrecacheParticleSystem( "doi_petrol_explosion_debris_f" )
PrecacheParticleSystem( "doi_petrol_explosion_fire_trail_b" )
PrecacheParticleSystem( "doi_petrol_explosion_fire_trail" )
PrecacheParticleSystem( "doi_petrol_explosion_glow_b" )
PrecacheParticleSystem( "doi_petrol_explosion_debris_g" )
PrecacheParticleSystem( "doi_petrol_explosion_fire_drips_b" )
PrecacheParticleSystem( "doi_petrol_explosion_glow_c" )
PrecacheParticleSystem( "doi_petrol_explosion_glow" )
PrecacheParticleSystem( "doi_petrol_explosion_fire_b" )
PrecacheParticleSystem( "doi_petrol_explosion_fire_drips" )
PrecacheParticleSystem( "doi_petrol_explosion_smoke_trail" )
PrecacheParticleSystem( "doi_petrol_explosion_smoke_ground" )
PrecacheParticleSystem( "doi_petrol_explosion_smoke_trail_c" )
PrecacheParticleSystem( "doi_petrol_explosion_sparks" )
PrecacheParticleSystem( "doi_petrol_explosion_fire" )
PrecacheParticleSystem( "doi_petrol_explosion_smoke_trail_b" )
PrecacheParticleSystem( "doi_petrol_explosion" )
PrecacheParticleSystem( "doi_petrol_smoke_trail_groups" )
PrecacheParticleSystem( "doi_petrol_explosion_smoke_trails" )
PrecacheParticleSystem( "doi_petrol_explosion_smoke_trails_child" )
PrecacheParticleSystem( "doi_petrol_explosion_debris" )
PrecacheParticleSystem( "doi_petrol_explosion_debris_b" )
PrecacheParticleSystem( "doi_petrol_explosion_debris_c" )
PrecacheParticleSystem( "doi_petrol_explosion_debris_e" )
PrecacheParticleSystem( "doi_petrol_explosion_debris_d" )
PrecacheParticleSystem( "doi_petrol_explosion_smoke" )
PrecacheParticleSystem( "doi_petrol_flame_trail_groups" )
PrecacheParticleSystem( "doi_petrol_explosion_flame_trails" )
PrecacheParticleSystem( "doi_petrol_explosion_flame_trail_child" )
PrecacheParticleSystem( "doi_petrol_leak_stream" )
PrecacheParticleSystem( "doi_petrol_leak_splashes" )
PrecacheParticleSystem( "doi_petrol_leak" )
PrecacheParticleSystem( "doi_petrol_flameup_wave" )
PrecacheParticleSystem( "doi_petrol_flameup" )
PrecacheParticleSystem( "doi_petrol_flameup_smoke" )
PrecacheParticleSystem( "doi_petrol_flameup_flames_d" )
PrecacheParticleSystem( "doi_petrol_flameup_wave_c" )
PrecacheParticleSystem( "doi_petrol_flameup_groundfire" )
PrecacheParticleSystem( "doi_petrol_flameup_flames_b" )
PrecacheParticleSystem( "doi_petrol_flameup_wave_b" )
PrecacheParticleSystem( "doi_petrol_flameup_flames" )
PrecacheParticleSystem( "doi_petrol_flameup_flames_c" )
PrecacheParticleSystem( "doi_petrol_flameup_spray1" )
PrecacheParticleSystem( "doi_petrol_flameup_spray2" )
PrecacheParticleSystem( "doi_petrol_flameup_glow" )
PrecacheParticleSystem( "doi_petrol_flameup_glow_b" )
					    
PrecacheParticleSystem( "doi_frag_explosion_smoke_c" )
PrecacheParticleSystem( "doi_frag_explosion" )
PrecacheParticleSystem( "doi_frag_explosion_smoke_ring" )
PrecacheParticleSystem( "doi_frag_explosion_smoke_d" )
PrecacheParticleSystem( "doi_frag_explosion_smoke_ground" )
PrecacheParticleSystem( "doi_frag_explosion_spikes" )
PrecacheParticleSystem( "doi_frag_explosion_debris_rocks" )
PrecacheParticleSystem( "doi_frag_explosion_glow" )
PrecacheParticleSystem( "doi_frag_explosion_flame_c" )
PrecacheParticleSystem( "doi_frag_explosion_sparks_b" )
PrecacheParticleSystem( "doi_frag_explosion_glow_b" )
PrecacheParticleSystem( "doi_frag_explosionOLD" )
PrecacheParticleSystem( "doi_frag_explosion_smoke" )
PrecacheParticleSystem( "doi_frag_explosion_smoke_b" )
PrecacheParticleSystem( "doi_frag_explosion_flame" )
PrecacheParticleSystem( "doi_frag_explosion_sparks" )
PrecacheParticleSystem( "doi_frag_explosion_debris" )
PrecacheParticleSystem( "doi_frag_explosion_debris_b" )
PrecacheParticleSystem( "doi_frag_explosion_flash" )
PrecacheParticleSystem( "doi_frag_explosion_flame_b" )
					    
PrecacheParticleSystem( "doi_splinter_explosion" )
PrecacheParticleSystem( "doi_splinter_explosion_sparks_b" )
PrecacheParticleSystem( "doi_splinter_explosion_sparkBurst" )
PrecacheParticleSystem( "doi_splinter_explosion_sparks" )
PrecacheParticleSystem( "doi_splinter_explosion_sparks_c" )
PrecacheParticleSystem( "doi_splinter_explosion_sparks_d" )
PrecacheParticleSystem( "doi_splinter_explosion_sparks_e" )
PrecacheParticleSystem( "doi_splinter_explosion_sparks_child" )
					    
PrecacheParticleSystem( "doi_ceilingDust_small" )
PrecacheParticleSystem( "doi_ceilingDust_small_b" )
PrecacheParticleSystem( "doi_ceilingDust_small_c" )
PrecacheParticleSystem( "doi_ceilingDust_small_debris" )
PrecacheParticleSystem( "doi_ceilingDust_large" )
PrecacheParticleSystem( "doi_ceilingDust_large_c" )
PrecacheParticleSystem( "doi_ceilingDust_large_b" )
PrecacheParticleSystem( "doi_ceilingDust_large_d" )
PrecacheParticleSystem( "doi_ceilingDust_large_debris" )
					    
PrecacheParticleSystem( "doi_smoke_artillery_explosion_spikes" )
PrecacheParticleSystem( "doi_smoke_artillery_explosion_smoke" )
PrecacheParticleSystem( "doi_smoke_artillery_explosion_flash" )
PrecacheParticleSystem( "doi_smoke_artillery_explosion_spikes_b" )
PrecacheParticleSystem( "doi_smoke_artillery_explosion_smoke_linger" )
PrecacheParticleSystem( "doi_smoke_artillery_explosion_spikes_c" )
PrecacheParticleSystem( "doi_smoke_artillery_explosion_smoke_c" )
PrecacheParticleSystem( "doi_smoke_artillery" )
PrecacheParticleSystem( "doi_smoke_artillery_explosion_smoke_b" )
PrecacheParticleSystem( "doi_smoke_artillery_explosion_smoke_d" )
					    
PrecacheParticleSystem( "doi_stuka_explosion" )
PrecacheParticleSystem( "doi_stuka_explosion_spikes_target" )
PrecacheParticleSystem( "doi_stuka_explosion_spikes" )
PrecacheParticleSystem( "doi_stuka_explosion_smoke" )
PrecacheParticleSystem( "doi_stuka_explosion_spikes_debris_target" )
PrecacheParticleSystem( "doi_stuka_explosion_spikes_debris_burst" )
PrecacheParticleSystem( "doi_stuka_explosion_smoke_b" )
PrecacheParticleSystem( "doi_stuka_explosion_flame_b" )
PrecacheParticleSystem( "doi_stuka_explosion_spikes_fast" )
PrecacheParticleSystem( "doi_stuka_explosion_spikes_c" )
PrecacheParticleSystem( "doi_stuka_explosion_spikes_b" )
PrecacheParticleSystem( "doi_stuka_explosion_flame" )
PrecacheParticleSystem( "doi_stuka_explosion_debris_d" )
PrecacheParticleSystem( "doi_stuka_explosion_debris_c" )
PrecacheParticleSystem( "doi_stuka_explosion_debris_b" )
PrecacheParticleSystem( "doi_stuka_explosion_debris" )
PrecacheParticleSystem( "doi_stuka_explosion_glow" )
PrecacheParticleSystem( "doi_stuka_explosion_debris_rocks" )

PrecacheParticleSystem( "doi_gunrun_impact" )
PrecacheParticleSystem( "doi_gunrun_impact_smoke" )
PrecacheParticleSystem( "doi_gunrun_impact_spikes_fast" )
PrecacheParticleSystem( "doi_gunrun_impact_spikes_target" )
PrecacheParticleSystem( "doi_gunrun_impact_spikes_debris" )
PrecacheParticleSystem( "doi_gunrun_impact_debris" )
PrecacheParticleSystem( "doi_gunrun_impact_debris_b" )
PrecacheParticleSystem( "doi_gunrun_impact_flash" )
PrecacheParticleSystem( "doi_gunrun_impact_sparks" )
PrecacheParticleSystem( "doi_gunrun_impact_sparkBurst" )

PrecacheParticleSystem( "smokegrenade_a" )
PrecacheParticleSystem( "smokegrenade_b" )
PrecacheParticleSystem( "smokegrenade" )
PrecacheParticleSystem( "smokegrenade_spray" )
PrecacheParticleSystem( "smokegrenade_spray_b" )
PrecacheParticleSystem( "smokegrenade_flame" )
PrecacheParticleSystem( "smokegrenade_sparks" )
PrecacheParticleSystem( "smokegrenade_c" )
					    
PrecacheParticleSystem( "m203_smokegrenade_spikes" )
PrecacheParticleSystem( "m203_smokegrenade_spikes_b" )
PrecacheParticleSystem( "m203_smokegrenade_cloud" )
PrecacheParticleSystem( "m203_smokegrenade" )
PrecacheParticleSystem( "m203_smokegrenade_flame" )
PrecacheParticleSystem( "m203_smokegrenade_sparks" )








-------


game.AddParticles( "particles/ww2_ins_smokegrenade.pcf" )
PrecacheParticleSystem( "ww2_smokegrenade_a" )
PrecacheParticleSystem( "ww2_smokegrenade_b" )
PrecacheParticleSystem( "ww2_smokegrenade" )
PrecacheParticleSystem( "ww2_smokegrenade_spray" )
PrecacheParticleSystem( "ww2_smokegrenade_spray_b" )
PrecacheParticleSystem( "ww2_smokegrenade_flame" )
PrecacheParticleSystem( "ww2_smokegrenade_air" )
PrecacheParticleSystem( "ww2_smokegrenade_sparks" )
PrecacheParticleSystem( "ww2_smokegrenade_c" )



game.AddParticles( "particles/ww2_ins_grenade_fx.pcf" )
PrecacheParticleSystem( "ww2_grenade_explosion" )
PrecacheParticleSystem( "ww2_grenade_inner_explosion" )
PrecacheParticleSystem( "ww2_grenade_explosion_smoke" )
PrecacheParticleSystem( "ww2_grenade_explosion_sparks_b" )
PrecacheParticleSystem( "ww2_grenade_explosion_sparks" )
PrecacheParticleSystem( "ww2_grenade_water_explosion" )
PrecacheParticleSystem( "ww2_grenade_explosion_flames_b" )
PrecacheParticleSystem( "ww2_grenade_explosion_spikes_c" )
PrecacheParticleSystem( "ww2_grenade_inner_explosion_glow" )
PrecacheParticleSystem( "ww2_grenade_inner_explosion_debris" )
PrecacheParticleSystem( "ww2_grenade_flash" )
PrecacheParticleSystem( "ww2_grenade_generic_nearglow" )
PrecacheParticleSystem( "ww2_grenade_flash_ground" )
PrecacheParticleSystem( "ww2_grenade_water_explosion_splash" )
PrecacheParticleSystem( "ww2_grenade_explosion_sparks_trails_b" )



game.AddParticles( "particles/ww2_ins_dynamite.pcf" )
PrecacheParticleSystem( "ww2_dynamite_explosion_shockwave" )
PrecacheParticleSystem( "ww2_dynamite_explosion_inner" )
PrecacheParticleSystem( "ww2_dynamite_explosion_spikes_b" )
PrecacheParticleSystem( "ww2_dynamite_explosion_g_smoke" )
PrecacheParticleSystem( "ww2_dynamite_explosion_debris_b" )
PrecacheParticleSystem( "ww2_dynamite_explosion_smoke_ground" )
PrecacheParticleSystem( "ww2_dynamite_explosion_flames_b" )
PrecacheParticleSystem( "ww2_dynamite_explosion_flames" )
PrecacheParticleSystem( "ww2_dynamite_explosion_nglow_b" )
PrecacheParticleSystem( "ww2_dynamite_explosion_sparks_e_tracers" )
PrecacheParticleSystem( "ww2_dynamite_explosion_flames_d" )
PrecacheParticleSystem( "ww2_dynamite_explosion_smoke_c" )
PrecacheParticleSystem( "ww2_dynamite_explosion_sparks_c" )
PrecacheParticleSystem( "ww2_dynamite_explosion_spikes_d" )
PrecacheParticleSystem( "ww2_dynamite_explosion_sparks_e" )
PrecacheParticleSystem( "ww2_dynamite_explosion_nglow" )
PrecacheParticleSystem( "ww2_dynamite_explosion_smoke" )
PrecacheParticleSystem( "ww2_dynamite_explosion_sparks_burst" )
PrecacheParticleSystem( "ww2_dynamite_explosion_spikes_c" )
PrecacheParticleSystem( "ww2_dynamite_explosion_smoke_b" )
PrecacheParticleSystem( "ww2_dynamite_explosion_sparks_b" )
PrecacheParticleSystem( "ww2_dynamite_explosion_smoke_thin" )
PrecacheParticleSystem( "ww2_dynamite_explosion_flash_b" )
PrecacheParticleSystem( "ww2_dynamite_explosion_trails_b" )
PrecacheParticleSystem( "ww2_dynamite_explosion_smoke_d" )
PrecacheParticleSystem( "ww2_dynamite_explosion_sparks_group" )
PrecacheParticleSystem( "ww2_dynamite_explosion" )
PrecacheParticleSystem( "ww2_dynamite_explosion_smoke_thin_b" )
PrecacheParticleSystem( "ww2_dynamite_explosion_flames_c" )
PrecacheParticleSystem( "ww2_dynamite_explosion_sparks" )
PrecacheParticleSystem( "ww2_dynamite_explosion_debris" )
PrecacheParticleSystem( "ww2_dynamite_explosion_spikes" )
PrecacheParticleSystem( "ww2_dynamite_explosion_flash" )
